[package]
edition = "2021"
exclude = ["index.node"]
name = "my-native"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = {version = "0.10", default-features = false, features = ["napi-6"]}
